spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
    resources:
      static-locations: file:src/main/resources/static/
      cache-period: 0
  resources:
    chain:
      cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/user_crm
    password: root
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: DEBUG